# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a75a313d032c0590bbfb1446a6a27063fcd742fce10a38db319813e99a0515f77fb934f293cdcc05b5a0de06b955eb2bcb6f02b089112c6bd21d90d911dea693

test:
  secret_key_base: d3bd244c28fbcb13b65332e78181f654669307e2c86b139e5f920e804909a83033cfe5f48cf058cfdf4a893681146d5b30843b1aebd28cb90450e5408dcfa2e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
